var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/design-system/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1q014pl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0cpzlvw.js")
R.c("server/chunks/ssr/_0ba3qxj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13d_o6g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0100oqz._.js")
R.c("server/chunks/ssr/_0g1m3-k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_design-system_page_actions_02ayg9d.js")
R.m(38572)
module.exports=R.m(38572).exports
