var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/command/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__144eb5b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1_k4w92.js")
R.c("server/chunks/ssr/[root-of-the-server]__13d_o6g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0100oqz._.js")
R.c("server/chunks/ssr/_0g1m3-k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_command_page_actions_0-y15um.js")
R.m(36767)
module.exports=R.m(36767).exports
